import { motifRegistry } from "@/data/motifs";
import type { MotifCategory, MotifDefinition } from "@/types/dream";
import type { RegistryIssue, RegistryIssueSeverity } from "./validateRegistry";
import { validateMotifRegistry } from "./validateRegistry";

export const relationReviewKinds = [
  "intentional-one-way",
  "should-be-reciprocal",
  "should-be-conflict",
  "generic-specific",
  "context-helper",
  "stale-relation",
] as const;

export type RelationReviewKind = (typeof relationReviewKinds)[number];

export const relationPriorityClusters = [
  "water-weather",
  "home-place",
  "movement",
  "communication",
  "relationship",
  "body-appearance",
  "emotion-action",
  "nature-sky",
  "object-record",
  "care-risk",
  "general",
] as const;

export type RelationPriorityCluster = (typeof relationPriorityClusters)[number];

export type RelationReviewRecord = {
  sourceId: string;
  targetId: string;
  sourceCategory: MotifCategory;
  targetCategory: MotifCategory;
  issueSeverity: RegistryIssueSeverity;
  relationType: "conflict" | "neighbor";
  cluster: RelationPriorityCluster;
  reviewKind: RelationReviewKind;
  priority: "high" | "normal";
  rationale: string;
};

export type RelationReviewSummary = {
  totalOneWayRelations: number;
  oneWayInfoRelations: number;
  oneWayWarningRelations: number;
  byKind: Record<RelationReviewKind, number>;
  byCluster: Record<RelationPriorityCluster, number>;
  highPriorityCount: number;
};

const priorityClusterIds = new Set([
  "water",
  "sea",
  "rain",
  "river",
  "house",
  "childhood_home",
  "hotel",
  "key",
  "toilet",
  "mirror",
  "station",
  "train",
  "bus",
  "car",
  "airport",
  "travel",
  "road",
  "bridge",
  "stairs",
  "elevator",
  "smartphone",
  "notification",
  "sns",
  "email",
  "phone",
  "letter",
  "friend",
  "family",
  "stranger",
  "ex_partner",
  "crush",
  "breakup",
  "naked",
  "injury",
  "voiceless",
  "blood",
  "hospital",
  "clothes",
  "hair",
  "teeth",
  "crying",
  "laughing",
  "apologizing",
  "being_chased",
  "fighting",
  "hiding",
  "searching",
  "waiting",
  "sky",
  "moon",
  "sun",
  "stars",
  "bird",
  "thunder",
  "wind",
  "snow",
  "photo",
  "clock",
  "wallet",
  "bag",
  "umbrella",
  "ring",
  "shop",
  "library",
  "park",
  "parking_lot",
  "book",
  "notebook",
  "box",
  "door",
  "picking_up",
  "choosing",
  "opening",
  "screaming",
  "forgetting",
  "eye",
  "trembling",
  "flower",
  "tree",
  "fish",
  "password",
  "chat",
  "restaurant",
  "cafe",
  "convenience_store",
  "map",
  "ticket",
  "cinema",
  "crossroad",
  "window",
  "desk",
  "chair",
  "running",
  "cleaning",
  "tidying",
  "losing",
  "handing_over",
  "cloud",
  "rainbow",
  "insect",
  "charging",
  "calendar",
  "hand",
  "foot",
  "voice",
  "horse",
  "sand",
  "embracing",
  "news",
  "past",
  "boss",
  "glasses",
  "child",
  "stone",
  "rooftop",
  "hot_spring",
  "game",
  "earphone",
  "dark",
  "pain",
  "sleep",
  "breaking",
  "kitchen",
  "garden",
  "pen",
  "dish",
  "hallway",
  "balcony",
  "television",
  "radio",
  "hat",
  "lake",
  "mask",
  "making_mistake",
  "refusing",
  "lining_up",
  "tripping",
  "pond",
  "fog",
  "mobile_app",
  "video",
  "teacher",
  "morning",
  "evening",
  "neighbor",
  "shelf",
  "gift",
  "entrance",
  "makeup",
  "inviting",
  "planner",
  "music",
  "comment",
  "streaming",
  "coworker",
  "tears",
  "concealing",
  "cooking",
  "shadow",
  "storage_room",
  "festival",
  "maze",
  "cup",
  "candle",
  "blanket",
  "envelope",
  "leaf",
  "wave",
  "ice",
  "face",
  "writing",
  "dancing",
  "scissors",
  "toy",
  "grass",
  "ear",
  "mouth",
  "breath",
  "swimming",
  "packing",
  "bicycle",
  "classmate",
  "seed",
  "soap",
  "pillow",
  "rope",
  "painting",
  "button",
  "towel",
  "coin",
  "folding",
  "climbing",
  "brush",
  "scarf",
  "forehead",
  "back",
  "scar",
  "carrying",
  "singing",
  "reading",
  "washing",
  "tying",
  "feather",
  "ribbon",
  "lantern",
  "drawer",
  "thread",
  "stamp",
  "clay",
  "shell",
  "bead",
  "spoon",
  "blank_page",
  "necklace",
  "shoulder",
  "wiping",
  "wrapping",
  "unpacking",
  "knot",
  "sleeve",
  "ankle",
  "carving",
  "postcard",
  "basket",
  "jar",
  "bench",
  "curtain",
  "nest",
  "chalk",
  "pebble",
  "maple_leaf",
  "tray",
  "needle",
  "paintbrush",
  "ladder",
  "glove",
  "plate",
  "lamp",
  "string",
  "marble",
  "bucket",
  "comb",
  "pinecone",
  "acorn",
  "mushroom",
  "fern",
  "dew",
  "broom",
  "bowl",
  "compass",
  "pencil",
  "bookmark",
  "shoelace",
  "zipper",
  "apron",
  "suitcase",
  "ticket_stub",
  "paint",
  "footprint",
  "eyelash",
  "keychain",
  "pocket",
  "twig",
  "moss",
  "petal",
  "raindrop",
  "eraser",
  "ruler",
  "paperclip",
  "coaster",
  "handkerchief",
  "bell",
  "backpack",
  "ink",
  "torn_paper",
  "dust",
  "stain",
  "answer_sheet",
  "keyboard",
  "monitor",
  "footsteps",
  "dead_end",
  "clover",
  "dandelion",
  "sprout",
  "bark",
  "vine",
  "glue",
  "tape",
  "label",
  "folder",
  "receipt",
  "magnifying_glass",
  "clipboard",
  "stapler",
  "calendar_page",
  "traffic_light",
  "crosswalk",
  "detour",
  "turn_back",
  "fingernail",
  "cheek",
  "root",
  "bud",
  "wildflower",
  "lichen",
  "reed",
  "rubber_band",
  "binder",
  "index_card",
  "coupon",
  "pencil_case",
  "sidewalk",
  "escalator",
  "platform_edge",
  "lost_ticket",
  "checklist",
  "progress_bar",
  "loading_icon",
  "eyebrow",
  "chin",
  "wristwatch",
  "pine_needle",
  "berry",
  "daisy",
  "waterweed",
  "driftwood",
  "rubber_stamp",
  "notepad",
  "sticky_note",
  "paper_cup",
  "file_tab",
  "pedestrian_bridge",
  "ticket_gate",
  "platform_sign",
  "pause_button",
  "status_light",
  "screen_corner",
  "name_tag",
  "paper_crane",
  "temple",
  "jawline",
  "willow",
  "lotus",
  "butterfly",
  "dragonfly",
  "owl",
  "paper_bag",
  "coin_purse",
  "corkboard",
  "measuring_tape",
  "ink_pad",
  "ticket_machine",
  "departure_board",
  "platform_clock",
  "cursor",
  "battery_icon",
  "mute_button",
  "nape",
  "eyelid",
  "hesitating",
  "backing_away",
  "camellia",
  "ivy",
  "firefly",
  "lily_pad",
  "sparrow",
  "binder_clip",
  "sketchbook",
  "stamp_sheet",
  "hourglass",
  "paperweight",
  "station_map",
  "route_sign",
  "search_bar",
  "signal_bar",
  "volume_slider",
  "collarbone",
  "flinching",
  "tiptoeing",
  "holding_back",
  "double_checking",
  "dragon",
  "angel",
  "lion",
  "giving_birth",
  "money",
  "spider",
  "bear",
  "wolf",
  "god",
  "demon",
  "airplane",
  "sword",
  "cave",
  "island",
  "volcano",
  "crowd",
  "whale",
  "fox",
  "desert",
  "remote_control",
  "water_bottle",
  "toothbrush",
  "keyhole",
  "doormat",
  "trash_can",
  "refrigerator",
  "living_room",
  "bedroom",
  "garage",
  "closet",
  "receiving",
  "borrowing",
  "lending",
  "throwing_away",
  "rabbit",
  "frog",
  "turtle",
  "nurse",
  "grandparent",
  "microwave",
  "kettle",
  "laundry_basket",
  "charging_cable",
  "shampoo_bottle",
  "bus_stop",
  "bakery",
  "deer",
  "squirrel",
  "returning",
  "mirror_cabinet",
  "post_office",
  "playground",
  "buying",
  "paying",
  "asking",
  "answering",
  "bee",
  "cousin",
  "coach",
]);

const genericSpecificGroups = [
  ["water", "sea", "river", "toilet"],
  ["water", "sea", "river", "toilet", "fish"],
  ["water", "sea", "river", "lake", "pond"],
  ["house", "childhood_home", "hotel", "key", "door", "opening"],
  ["house", "kitchen", "garden", "hallway", "balcony"],
  ["travel", "train", "bus", "car", "ship", "airport", "station"],
  ["road", "bridge", "stairs", "elevator", "lost"],
  ["clothes", "naked", "hair", "teeth", "mirror"],
  ["death", "breakup", "ex_partner", "ring"],
  ["book", "notebook", "library", "school"],
  ["password", "key", "smartphone", "sns"],
  ["mobile_app", "smartphone", "notification", "password"],
  ["television", "video", "cinema", "news"],
  ["teacher", "school", "exam", "boss"],
  ["television", "video", "cinema", "news", "streaming"],
  ["sns", "chat", "comment", "streaming", "notification"],
  ["house", "entrance", "door", "shoes", "key"],
  ["house", "storage_room", "shelf", "box", "past"],
  ["calendar", "planner", "notebook", "being_late", "forgetting"],
  ["crying", "tears", "rain", "water"],
  ["hiding", "concealing", "box", "mask"],
  ["lost", "maze", "road", "searching"],
  ["ticket", "station", "train", "travel"],
  ["map", "road", "travel", "lost"],
  ["window", "house", "door", "sky"],
  ["losing", "lost", "wallet", "key", "bag", "ticket", "phone"],
  ["charging", "smartphone", "notification", "cafe"],
  ["calendar", "clock", "being_late", "forgetting"],
  ["cup", "water", "kitchen", "dish"],
  ["envelope", "letter", "gift", "opening"],
  ["face", "mirror", "makeup", "mask"],
  ["writing", "pen", "notebook", "letter"],
  ["classmate", "school", "friend", "teacher"],
  ["seed", "leaf", "tree", "flower"],
  ["soap", "washing", "cleaning", "water", "towel"],
  ["pillow", "sleep", "blanket", "breath"],
  ["rope", "tying", "climbing", "falling"],
  ["painting", "face", "mirror", "past"],
  ["button", "clothes", "choosing", "opening"],
  ["towel", "water", "cleaning", "soap"],
  ["coin", "wallet", "shop", "choosing"],
  ["folding", "clothes", "tidying", "blanket"],
  ["climbing", "stairs", "mountain", "rope"],
  ["brush", "hair", "cleaning", "mirror"],
  ["scarf", "clothes", "wind", "hat"],
  ["forehead", "face", "hair", "hand"],
  ["back", "carrying", "pain", "hand"],
  ["scar", "injury", "past", "mirror"],
  ["carrying", "bag", "hand", "packing"],
  ["singing", "mouth", "breath", "dancing"],
  ["reading", "book", "notebook", "writing"],
  ["washing", "cleaning", "water", "towel"],
  ["tying", "rope", "hand", "packing"],
  ["feather", "bird", "wind", "sky"],
  ["ribbon", "clothes", "gift", "tying"],
  ["lantern", "candle", "dark", "festival"],
  ["drawer", "desk", "box", "tidying"],
  ["thread", "tying", "clothes", "rope"],
  ["stamp", "letter", "envelope", "past"],
  ["clay", "hand", "child", "making_mistake"],
  ["shell", "sea", "sand", "past"],
  ["bead", "gift", "clothes", "coin"],
  ["spoon", "dish", "cooking", "cup"],
  ["blank_page", "notebook", "writing", "reading"],
  ["necklace", "clothes", "gift", "bead"],
  ["shoulder", "back", "hand", "carrying"],
  ["wiping", "towel", "cleaning", "washing"],
  ["wrapping", "gift", "ribbon", "blanket"],
  ["unpacking", "packing", "bag", "travel"],
  ["knot", "rope", "tying", "thread"],
  ["sleeve", "clothes", "hand", "scarf"],
  ["ankle", "foot", "shoes", "tripping"],
  ["carving", "clay", "hand", "stone"],
  ["postcard", "stamp", "photo", "travel"],
  ["basket", "bag", "gift", "carrying"],
  ["jar", "cup", "water", "shelf"],
  ["bench", "waiting", "chair", "road"],
  ["curtain", "shadow", "clothes", "opening"],
  ["nest", "bird", "tree", "baby"],
  ["chalk", "writing", "school", "hand"],
  ["pebble", "stone", "road", "river"],
  ["maple_leaf", "leaf", "tree", "wind"],
  ["tray", "dish", "cup", "carrying"],
  ["needle", "thread", "clothes", "hand"],
  ["paintbrush", "painting", "brush", "hand"],
  ["ladder", "stairs", "climbing", "falling"],
  ["glove", "hand", "clothes", "scarf"],
  ["plate", "dish", "cooking", "spoon"],
  ["lamp", "lantern", "candle", "dark"],
  ["string", "thread", "knot", "tying"],
  ["marble", "bead", "coin", "game"],
  ["bucket", "water", "cleaning", "carrying"],
  ["comb", "hair", "brush", "mirror"],
  ["pinecone", "tree", "seed", "forest"],
  ["acorn", "seed", "tree", "child"],
  ["mushroom", "forest", "rain", "grass"],
  ["fern", "leaf", "forest", "shadow"],
  ["dew", "morning", "grass", "water"],
  ["broom", "cleaning", "tidying", "hand"],
  ["bowl", "dish", "cooking", "cup"],
  ["compass", "map", "travel", "road"],
  ["pencil", "writing", "notebook", "hand"],
  ["bookmark", "book", "reading", "notebook"],
  ["shoelace", "shoes", "tying", "string"],
  ["zipper", "clothes", "opening", "button"],
  ["apron", "cooking", "clothes", "towel"],
  ["suitcase", "bag", "travel", "packing"],
  ["ticket_stub", "ticket", "past", "photo"],
  ["paint", "painting", "paintbrush", "brush"],
  ["footprint", "foot", "road", "past"],
  ["eyelash", "eye", "face", "makeup"],
  ["keychain", "key", "bag", "gift"],
  ["pocket", "clothes", "bag", "coin"],
  ["twig", "tree", "forest", "hand"],
  ["moss", "stone", "forest", "water"],
  ["petal", "flower", "wind", "past"],
  ["raindrop", "rain", "water", "dew"],
  ["eraser", "pencil", "writing", "notebook"],
  ["ruler", "school", "pencil", "desk"],
  ["paperclip", "notebook", "blank_page", "desk"],
  ["coaster", "cup", "tray", "dish"],
  ["handkerchief", "tears", "wiping", "pocket"],
  ["bell", "music", "festival", "voice"],
  ["backpack", "bag", "packing", "travel"],
  ["ink", "pen", "writing", "paint"],
  ["torn_paper", "blank_page", "breaking", "writing"],
  ["dust", "cleaning", "shadow", "past"],
  ["stain", "washing", "clothes", "towel"],
  ["answer_sheet", "exam", "pen", "school"],
  ["keyboard", "desk", "writing", "workplace"],
  ["monitor", "desk", "television", "video"],
  ["footsteps", "being_chased", "running", "foot"],
  ["dead_end", "road", "maze", "lost"],
  ["clover", "grass", "flower", "choosing"],
  ["dandelion", "flower", "wind", "grass"],
  ["sprout", "seed", "leaf", "tree"],
  ["bark", "tree", "forest", "scar"],
  ["vine", "leaf", "tying", "rope"],
  ["glue", "torn_paper", "paperclip", "writing"],
  ["tape", "glue", "box", "wrapping"],
  ["label", "box", "writing", "shelf"],
  ["folder", "notebook", "paperclip", "desk"],
  ["receipt", "wallet", "shop", "past"],
  ["magnifying_glass", "glasses", "searching", "book"],
  ["clipboard", "paperclip", "answer_sheet", "desk"],
  ["stapler", "paperclip", "folder", "desk"],
  ["calendar_page", "calendar", "being_late", "planner"],
  ["traffic_light", "crossroad", "road", "waiting"],
  ["crosswalk", "road", "traffic_light", "crossroad"],
  ["detour", "road", "lost", "dead_end"],
  ["turn_back", "dead_end", "road", "lost"],
  ["fingernail", "hand", "makeup", "mirror"],
  ["cheek", "face", "mirror", "makeup"],
  ["root", "tree", "seed", "forest"],
  ["bud", "flower", "sprout", "seed"],
  ["wildflower", "flower", "grass", "park"],
  ["lichen", "moss", "stone", "forest"],
  ["reed", "water", "river", "grass"],
  ["rubber_band", "string", "tying", "paperclip"],
  ["binder", "folder", "paperclip", "desk"],
  ["index_card", "notebook", "writing", "exam"],
  ["coupon", "wallet", "shop", "receipt"],
  ["pencil_case", "pencil", "eraser", "desk"],
  ["sidewalk", "road", "crosswalk", "foot"],
  ["escalator", "stairs", "elevator", "climbing"],
  ["platform_edge", "station", "train", "being_late"],
  ["lost_ticket", "ticket", "losing", "train"],
  ["checklist", "clipboard", "planner", "making_mistake"],
  ["progress_bar", "monitor", "waiting", "clock"],
  ["loading_icon", "monitor", "waiting", "clock"],
  ["eyebrow", "face", "makeup", "mirror"],
  ["chin", "face", "mirror", "cheek"],
  ["wristwatch", "clock", "being_late", "calendar_page"],
  ["pine_needle", "pinecone", "tree", "leaf"],
  ["berry", "seed", "tree", "basket"],
  ["daisy", "flower", "wildflower", "clover"],
  ["waterweed", "water", "river", "grass"],
  ["driftwood", "tree", "river", "sea"],
  ["rubber_stamp", "stamp", "ink", "desk"],
  ["notepad", "notebook", "writing", "pencil"],
  ["sticky_note", "label", "notebook", "desk"],
  ["paper_cup", "cup", "tray", "dish"],
  ["file_tab", "folder", "label", "binder"],
  ["pedestrian_bridge", "bridge", "sidewalk", "crosswalk"],
  ["ticket_gate", "station", "ticket", "train"],
  ["platform_sign", "platform_edge", "station", "train"],
  ["pause_button", "progress_bar", "loading_icon", "monitor"],
  ["status_light", "traffic_light", "monitor", "waiting"],
  ["screen_corner", "monitor", "loading_icon", "shadow"],
  ["name_tag", "label", "clothes", "mirror"],
  ["paper_crane", "folding", "blank_page", "bird"],
  ["temple", "face", "forehead", "mirror"],
  ["jawline", "chin", "face", "cheek"],
  ["willow", "tree", "wind", "river"],
  ["lotus", "flower", "pond", "water"],
  ["butterfly", "flower", "wind", "insect"],
  ["dragonfly", "insect", "pond", "water"],
  ["owl", "bird", "dark", "tree"],
  ["paper_bag", "bag", "shop", "gift"],
  ["coin_purse", "wallet", "coin", "bag"],
  ["corkboard", "sticky_note", "notepad", "label"],
  ["measuring_tape", "ruler", "clothes", "hand"],
  ["ink_pad", "stamp", "rubber_stamp", "ink"],
  ["ticket_machine", "ticket", "station", "train"],
  ["departure_board", "platform_sign", "station", "train"],
  ["platform_clock", "clock", "station", "being_late"],
  ["cursor", "monitor", "screen_corner", "loading_icon"],
  ["battery_icon", "charging", "monitor", "status_light"],
  ["mute_button", "pause_button", "voice", "monitor"],
  ["nape", "hair", "necklace", "shoulder"],
  ["eyelid", "eye", "eyelash", "eyebrow"],
  ["hesitating", "choosing", "waiting", "turn_back"],
  ["backing_away", "being_chased", "fighting", "hiding"],
  ["camellia", "flower", "tree", "evening"],
  ["ivy", "vine", "tree", "garden"],
  ["firefly", "insect", "dark", "forest"],
  ["lily_pad", "lotus", "pond", "water"],
  ["sparrow", "bird", "morning", "tree"],
  ["binder_clip", "paperclip", "folder", "receipt"],
  ["sketchbook", "notebook", "blank_page", "painting"],
  ["stamp_sheet", "stamp", "letter", "postcard"],
  ["hourglass", "clock", "sand", "waiting"],
  ["paperweight", "desk", "book", "paperclip"],
  ["station_map", "station", "train", "ticket_gate"],
  ["route_sign", "platform_sign", "detour", "station"],
  ["search_bar", "cursor", "monitor", "searching"],
  ["signal_bar", "status_light", "mobile_app", "monitor"],
  ["volume_slider", "mute_button", "voice", "monitor"],
  ["collarbone", "necklace", "shoulder", "nape"],
  ["flinching", "fighting", "being_chased", "backing_away"],
  ["tiptoeing", "hiding", "hallway", "being_chased"],
  ["holding_back", "hesitating", "backing_away", "fighting"],
  ["double_checking", "making_mistake", "searching", "choosing"],
  ["dragon", "snake", "flying", "sea"],
  ["angel", "flying", "sky", "guide"],
  ["lion", "being_chased", "mountain", "cat"],
  ["giving_birth", "baby", "pregnancy", "family"],
  ["money", "wallet", "coin", "treasure"],
  ["spider", "insect", "dark", "being_chased"],
  ["bear", "mountain", "forest", "being_chased"],
  ["wolf", "dog", "being_chased", "forest"],
  ["god", "shrine", "angel", "guide"],
  ["demon", "being_chased", "dark", "ghost"],
  ["airplane", "airport", "travel", "flying", "sky"],
  ["sword", "fighting", "injury", "scissors"],
  ["cave", "dark", "forest", "mountain"],
  ["island", "sea", "ship", "travel"],
  ["volcano", "fire", "mountain", "thunder"],
  ["crowd", "stranger", "festival", "waiting"],
  ["whale", "sea", "water", "fish"],
  ["fox", "forest", "shrine", "dark"],
  ["desert", "sand", "road", "sun"],
  ["remote_control", "television", "video", "choosing"],
  ["water_bottle", "water", "bag", "travel"],
  ["toothbrush", "teeth", "washing", "morning"],
  ["keyhole", "key", "door", "entrance"],
  ["doormat", "entrance", "house", "shoes"],
  ["trash_can", "cleaning", "tidying", "throwing_away"],
  ["refrigerator", "kitchen", "cooking", "storage_room"],
  ["living_room", "house", "television", "family"],
  ["bedroom", "sleep", "blanket", "pillow"],
  ["garage", "car", "house", "storage_room"],
  ["closet", "clothes", "hiding", "storage_room"],
  ["receiving", "handing_over", "gift", "letter"],
  ["borrowing", "lending", "receiving", "handing_over"],
  ["throwing_away", "tidying", "cleaning", "trash_can"],
  ["rabbit", "child", "family", "grass"],
  ["frog", "rain", "pond", "water"],
  ["turtle", "water", "pond", "shell"],
  ["nurse", "hospital", "injury", "hand"],
  ["grandparent", "family", "ancestor", "past"],
  ["microwave", "kitchen", "cooking", "waiting"],
  ["kettle", "kitchen", "water", "fire"],
  ["laundry_basket", "washing", "clothes", "tidying"],
  ["charging_cable", "charging", "smartphone", "battery_icon"],
  ["shampoo_bottle", "hair", "washing", "toilet"],
  ["bus_stop", "bus", "waiting", "road"],
  ["bakery", "shop", "morning", "buying"],
  ["deer", "forest", "shrine", "grass"],
  ["squirrel", "tree", "park", "concealing"],
  ["returning", "borrowing", "lending", "apologizing"],
  ["mirror_cabinet", "mirror", "makeup", "hair"],
  ["post_office", "letter", "receiving", "waiting"],
  ["playground", "child", "park", "family"],
  ["buying", "shop", "wallet", "choosing"],
  ["paying", "wallet", "money", "shop"],
  ["asking", "voice", "chat", "teacher"],
  ["answering", "voice", "exam", "phone"],
  ["bee", "insect", "flower", "workplace"],
  ["cousin", "family", "childhood_home", "grandparent"],
  ["coach", "teacher", "mentor", "boss"],
];

const reciprocalCandidateGroups = [
  ["smartphone", "notification", "sns", "email", "phone", "letter", "chat", "password"],
  ["station", "train", "bus", "airport", "travel"],
  ["clock", "being_late", "waiting", "notification"],
  ["injury", "blood", "hospital", "fighting"],
  ["sky", "moon", "sun", "stars", "bird", "flying"],
  ["rain", "thunder", "wind", "snow", "sky"],
  ["friend", "family", "stranger", "ex_partner", "crush"],
  ["shop", "bag", "wallet", "clothes", "choosing"],
  ["library", "book", "notebook", "school", "exam"],
  ["park", "flower", "tree", "bird", "friend", "family"],
  ["door", "opening", "box", "key", "house"],
  ["screaming", "voiceless", "being_chased", "fighting"],
  ["eye", "mirror", "stranger", "photo"],
  ["trembling", "thunder", "injury", "voiceless"],
  ["restaurant", "cafe", "convenience_store", "shop", "wallet"],
  ["cinema", "ticket", "photo", "eye"],
  ["crossroad", "road", "choosing", "lost"],
  ["desk", "chair", "school", "workplace", "notebook"],
  ["running", "being_chased", "being_late", "road"],
  ["cleaning", "tidying", "house", "desk", "box", "bag"],
  ["handing_over", "letter", "ticket", "ring"],
  ["cloud", "rainbow", "sky", "rain", "sun"],
  ["insect", "forest", "park", "cat"],
  ["boss", "workplace", "exam", "being_late", "school"],
  ["hand", "foot", "voice", "trembling", "screaming"],
  ["sand", "sea", "water", "river"],
  ["embracing", "family", "friend", "crush"],
  ["news", "smartphone", "notification", "sns"],
  ["past", "childhood_home", "ex_partner", "letter"],
  ["child", "family", "baby", "school"],
  ["stone", "mountain", "river", "road"],
  ["dark", "moon", "hiding", "being_chased"],
  ["pain", "injury", "blood", "trembling"],
  ["sleep", "dark", "moon", "house"],
  ["breaking", "fighting", "fire", "injury"],
  ["game", "smartphone", "exam", "choosing"],
  ["earphone", "smartphone", "voice", "phone"],
  ["rooftop", "sky", "falling", "flying"],
  ["hot_spring", "water", "travel", "cleaning"],
  ["glasses", "eye", "mirror", "photo", "book"],
  ["kitchen", "house", "cleaning", "restaurant", "dish"],
  ["garden", "house", "flower", "tree", "park"],
  ["pen", "notebook", "letter", "exam"],
  ["hallway", "school", "hospital", "hotel", "door"],
  ["balcony", "house", "sky", "wind"],
  ["television", "news", "cinema", "video"],
  ["radio", "voice", "news", "earphone"],
  ["morning", "sun", "calendar", "being_late"],
  ["evening", "sun", "past", "waiting"],
  ["neighbor", "house", "stranger", "friend"],
  ["shelf", "book", "tidying", "box"],
  ["gift", "handing_over", "opening", "choosing"],
  ["entrance", "house", "door", "shoes"],
  ["makeup", "mirror", "clothes", "mask"],
  ["inviting", "friend", "crush", "refusing"],
  ["planner", "calendar", "notebook", "bag"],
  ["music", "radio", "earphone", "voice"],
  ["comment", "sns", "chat", "video"],
  ["streaming", "video", "sns", "comment"],
  ["coworker", "workplace", "boss", "friend"],
  ["tears", "crying", "rain", "mirror"],
  ["concealing", "hiding", "box", "mask"],
  ["cooking", "kitchen", "restaurant", "dish"],
  ["shadow", "dark", "sun", "mirror"],
  ["storage_room", "box", "shelf", "past"],
  ["festival", "park", "shrine", "music"],
  ["maze", "lost", "road", "searching"],
  ["cup", "water", "kitchen", "dish"],
  ["candle", "fire", "dark", "shrine"],
  ["blanket", "sleep", "house", "baby"],
  ["envelope", "letter", "gift", "opening"],
  ["leaf", "tree", "wind", "forest"],
  ["wave", "sea", "water", "ship"],
  ["ice", "water", "snow", "dark"],
  ["face", "mirror", "makeup", "mask"],
  ["writing", "pen", "notebook", "letter"],
  ["dancing", "music", "festival", "foot"],
  ["scissors", "hair", "clothes", "breaking"],
  ["toy", "child", "gift", "game"],
  ["grass", "park", "garden", "tree"],
  ["ear", "voice", "earphone", "music"],
  ["mouth", "voice", "teeth", "cooking"],
  ["breath", "running", "sleep", "trembling"],
  ["swimming", "water", "sea", "lake"],
  ["packing", "bag", "travel", "forgetting"],
  ["bicycle", "road", "shoes", "travel"],
  ["classmate", "school", "friend", "teacher"],
  ["seed", "leaf", "tree", "flower"],
  ["soap", "cleaning", "water", "towel"],
  ["pillow", "sleep", "blanket", "breath"],
  ["rope", "tying", "climbing", "falling"],
  ["painting", "face", "mirror", "past"],
  ["button", "clothes", "choosing", "opening"],
  ["towel", "water", "cleaning", "soap"],
  ["coin", "wallet", "shop", "choosing"],
  ["folding", "clothes", "tidying", "blanket"],
  ["climbing", "stairs", "mountain", "rope"],
  ["brush", "hair", "cleaning", "mirror"],
  ["scarf", "clothes", "wind", "hat"],
  ["forehead", "face", "hair", "hand"],
  ["back", "carrying", "pain", "hand"],
  ["scar", "injury", "past", "mirror"],
  ["carrying", "bag", "hand", "packing"],
  ["singing", "mouth", "breath", "dancing"],
  ["reading", "book", "notebook", "writing"],
  ["washing", "cleaning", "water", "towel"],
  ["tying", "rope", "hand", "packing"],
  ["feather", "bird", "wind", "sky"],
  ["ribbon", "clothes", "gift", "tying"],
  ["lantern", "candle", "dark", "festival"],
  ["drawer", "desk", "box", "tidying"],
  ["thread", "tying", "clothes", "rope"],
  ["stamp", "letter", "envelope", "past"],
  ["clay", "hand", "child", "making_mistake"],
  ["shell", "sea", "sand", "past"],
  ["bead", "gift", "clothes", "coin"],
  ["spoon", "dish", "cooking", "cup"],
  ["blank_page", "notebook", "writing", "reading"],
  ["necklace", "clothes", "gift", "bead"],
  ["shoulder", "back", "hand", "carrying"],
  ["wiping", "towel", "cleaning", "washing"],
  ["wrapping", "gift", "ribbon", "blanket"],
  ["unpacking", "packing", "bag", "travel"],
  ["knot", "rope", "tying", "thread"],
  ["sleeve", "clothes", "hand", "scarf"],
  ["ankle", "foot", "shoes", "tripping"],
  ["carving", "clay", "hand", "stone"],
  ["postcard", "stamp", "photo", "travel"],
  ["basket", "bag", "gift", "carrying"],
  ["jar", "cup", "water", "shelf"],
  ["bench", "waiting", "chair", "road"],
  ["curtain", "shadow", "clothes", "opening"],
  ["nest", "bird", "tree", "baby"],
  ["chalk", "writing", "school", "hand"],
  ["pebble", "stone", "road", "river"],
  ["maple_leaf", "leaf", "tree", "wind"],
  ["tray", "dish", "cup", "carrying"],
  ["needle", "thread", "clothes", "hand"],
  ["paintbrush", "painting", "brush", "hand"],
  ["ladder", "stairs", "climbing", "falling"],
  ["glove", "hand", "clothes", "scarf"],
  ["plate", "dish", "cooking", "spoon"],
  ["lamp", "lantern", "candle", "dark"],
  ["string", "thread", "knot", "tying"],
  ["marble", "bead", "coin", "game"],
  ["bucket", "water", "cleaning", "carrying"],
  ["comb", "hair", "brush", "mirror"],
  ["pinecone", "tree", "seed", "forest"],
  ["acorn", "seed", "tree", "child"],
  ["mushroom", "forest", "rain", "grass"],
  ["fern", "leaf", "forest", "shadow"],
  ["dew", "morning", "grass", "water"],
  ["broom", "cleaning", "tidying", "hand"],
  ["bowl", "dish", "cooking", "cup"],
  ["compass", "map", "travel", "road"],
  ["pencil", "writing", "notebook", "hand"],
  ["bookmark", "book", "reading", "notebook"],
  ["shoelace", "shoes", "tying", "string"],
  ["zipper", "clothes", "opening", "button"],
  ["apron", "cooking", "clothes", "towel"],
  ["suitcase", "bag", "travel", "packing"],
  ["ticket_stub", "ticket", "past", "photo"],
  ["paint", "painting", "paintbrush", "brush"],
  ["footprint", "foot", "road", "past"],
  ["eyelash", "eye", "face", "makeup"],
  ["keychain", "key", "bag", "gift"],
  ["pocket", "clothes", "bag", "coin"],
  ["twig", "tree", "forest", "hand"],
  ["moss", "stone", "forest", "water"],
  ["petal", "flower", "wind", "past"],
  ["raindrop", "rain", "water", "dew"],
  ["eraser", "pencil", "writing", "notebook"],
  ["ruler", "school", "pencil", "desk"],
  ["paperclip", "notebook", "blank_page", "desk"],
  ["coaster", "cup", "tray", "dish"],
  ["handkerchief", "tears", "wiping", "pocket"],
  ["bell", "music", "festival", "voice"],
  ["backpack", "bag", "packing", "travel"],
  ["ink", "pen", "writing", "paint"],
  ["torn_paper", "blank_page", "breaking", "writing"],
  ["dust", "cleaning", "shadow", "past"],
  ["stain", "washing", "clothes", "towel"],
  ["answer_sheet", "exam", "pen", "school"],
  ["keyboard", "desk", "writing", "workplace"],
  ["monitor", "desk", "television", "video"],
  ["footsteps", "being_chased", "running", "foot"],
  ["dead_end", "road", "maze", "lost"],
  ["clover", "grass", "flower", "choosing"],
  ["dandelion", "flower", "wind", "grass"],
  ["sprout", "seed", "leaf", "tree"],
  ["bark", "tree", "forest", "scar"],
  ["vine", "leaf", "tying", "rope"],
  ["glue", "torn_paper", "paperclip", "writing"],
  ["tape", "glue", "box", "wrapping"],
  ["label", "box", "writing", "shelf"],
  ["folder", "notebook", "paperclip", "desk"],
  ["receipt", "wallet", "shop", "past"],
  ["magnifying_glass", "glasses", "searching", "book"],
  ["clipboard", "paperclip", "answer_sheet", "desk"],
  ["stapler", "paperclip", "folder", "desk"],
  ["calendar_page", "calendar", "being_late", "planner"],
  ["traffic_light", "crossroad", "road", "waiting"],
  ["crosswalk", "road", "traffic_light", "crossroad"],
  ["detour", "road", "lost", "dead_end"],
  ["turn_back", "dead_end", "road", "lost"],
  ["fingernail", "hand", "makeup", "mirror"],
  ["cheek", "face", "mirror", "makeup"],
  ["root", "tree", "seed", "forest"],
  ["bud", "flower", "sprout", "seed"],
  ["wildflower", "flower", "grass", "park"],
  ["lichen", "moss", "stone", "forest"],
  ["reed", "water", "river", "grass"],
  ["rubber_band", "string", "tying", "paperclip"],
  ["binder", "folder", "paperclip", "desk"],
  ["index_card", "notebook", "writing", "exam"],
  ["coupon", "wallet", "shop", "receipt"],
  ["pencil_case", "pencil", "eraser", "desk"],
  ["sidewalk", "road", "crosswalk", "foot"],
  ["escalator", "stairs", "elevator", "climbing"],
  ["platform_edge", "station", "train", "being_late"],
  ["lost_ticket", "ticket", "losing", "train"],
  ["checklist", "clipboard", "planner", "making_mistake"],
  ["progress_bar", "monitor", "waiting", "clock"],
  ["loading_icon", "monitor", "waiting", "clock"],
  ["eyebrow", "face", "makeup", "mirror"],
  ["chin", "face", "mirror", "cheek"],
  ["wristwatch", "clock", "being_late", "calendar_page"],
  ["pine_needle", "pinecone", "tree", "leaf"],
  ["berry", "seed", "tree", "basket"],
  ["daisy", "flower", "wildflower", "clover"],
  ["waterweed", "water", "river", "grass"],
  ["driftwood", "tree", "river", "sea"],
  ["rubber_stamp", "stamp", "ink", "desk"],
  ["notepad", "notebook", "writing", "pencil"],
  ["sticky_note", "label", "notebook", "desk"],
  ["paper_cup", "cup", "tray", "dish"],
  ["file_tab", "folder", "label", "binder"],
  ["pedestrian_bridge", "bridge", "sidewalk", "crosswalk"],
  ["ticket_gate", "station", "ticket", "train"],
  ["platform_sign", "platform_edge", "station", "train"],
  ["pause_button", "progress_bar", "loading_icon", "monitor"],
  ["status_light", "traffic_light", "monitor", "waiting"],
  ["screen_corner", "monitor", "loading_icon", "shadow"],
  ["name_tag", "label", "clothes", "mirror"],
  ["paper_crane", "folding", "blank_page", "bird"],
  ["temple", "face", "forehead", "mirror"],
  ["jawline", "chin", "face", "cheek"],
  ["willow", "tree", "wind", "river"],
  ["lotus", "flower", "pond", "water"],
  ["butterfly", "flower", "wind", "insect"],
  ["dragonfly", "insect", "pond", "water"],
  ["owl", "bird", "dark", "tree"],
  ["paper_bag", "bag", "shop", "gift"],
  ["coin_purse", "wallet", "coin", "bag"],
  ["corkboard", "sticky_note", "notepad", "label"],
  ["measuring_tape", "ruler", "clothes", "hand"],
  ["ink_pad", "stamp", "rubber_stamp", "ink"],
  ["ticket_machine", "ticket", "station", "train"],
  ["departure_board", "platform_sign", "station", "train"],
  ["platform_clock", "clock", "station", "being_late"],
  ["cursor", "monitor", "screen_corner", "loading_icon"],
  ["battery_icon", "charging", "monitor", "status_light"],
  ["mute_button", "pause_button", "voice", "monitor"],
  ["nape", "hair", "necklace", "shoulder"],
  ["eyelid", "eye", "eyelash", "eyebrow"],
  ["hesitating", "choosing", "waiting", "turn_back"],
  ["backing_away", "being_chased", "fighting", "hiding"],
  ["camellia", "flower", "tree", "evening"],
  ["ivy", "vine", "tree", "garden"],
  ["firefly", "insect", "dark", "forest"],
  ["lily_pad", "lotus", "pond", "water"],
  ["sparrow", "bird", "morning", "tree"],
  ["binder_clip", "paperclip", "folder", "receipt"],
  ["sketchbook", "notebook", "blank_page", "painting"],
  ["stamp_sheet", "stamp", "letter", "postcard"],
  ["hourglass", "clock", "sand", "waiting"],
  ["paperweight", "desk", "book", "paperclip"],
  ["station_map", "station", "train", "ticket_gate"],
  ["route_sign", "platform_sign", "detour", "station"],
  ["search_bar", "cursor", "monitor", "searching"],
  ["signal_bar", "status_light", "mobile_app", "monitor"],
  ["volume_slider", "mute_button", "voice", "monitor"],
  ["collarbone", "necklace", "shoulder", "nape"],
  ["flinching", "fighting", "being_chased", "backing_away"],
  ["tiptoeing", "hiding", "hallway", "being_chased"],
  ["holding_back", "hesitating", "backing_away", "fighting"],
  ["double_checking", "making_mistake", "searching", "choosing"],
  ["hat", "clothes", "mirror", "glasses"],
  ["lake", "water", "river", "forest"],
  ["mask", "voice", "mirror", "clothes"],
  ["making_mistake", "exam", "workplace", "apologizing"],
  ["refusing", "friend", "workplace", "apologizing"],
  ["lining_up", "waiting", "shop", "station"],
  ["tripping", "falling", "foot", "injury"],
  ["pond", "water", "fish", "park"],
  ["fog", "cloud", "lost", "road"],
  ["mobile_app", "smartphone", "notification", "password"],
  ["video", "television", "cinema", "sns"],
  ["teacher", "school", "exam", "boss"],
  ["dragon", "snake", "flying", "sea"],
  ["angel", "flying", "sky", "guide"],
  ["lion", "being_chased", "mountain", "cat"],
  ["giving_birth", "baby", "pregnancy", "family"],
  ["money", "wallet", "coin", "treasure"],
  ["spider", "insect", "dark", "being_chased"],
  ["bear", "mountain", "forest", "being_chased"],
  ["wolf", "dog", "being_chased", "forest"],
  ["god", "shrine", "angel", "guide"],
  ["demon", "being_chased", "dark", "ghost"],
  ["airplane", "airport", "travel", "flying", "sky"],
  ["sword", "fighting", "injury", "scissors"],
  ["cave", "dark", "forest", "mountain"],
  ["island", "sea", "ship", "travel"],
  ["volcano", "fire", "mountain", "thunder"],
  ["crowd", "stranger", "festival", "waiting"],
  ["whale", "sea", "water", "fish"],
  ["fox", "forest", "shrine", "dark"],
  ["desert", "sand", "road", "sun"],
  ["remote_control", "television", "video", "choosing"],
  ["water_bottle", "water", "bag", "travel"],
  ["toothbrush", "teeth", "washing", "morning"],
  ["keyhole", "key", "door", "entrance"],
  ["doormat", "entrance", "house", "shoes"],
  ["trash_can", "cleaning", "tidying", "throwing_away"],
  ["refrigerator", "kitchen", "cooking", "storage_room"],
  ["living_room", "house", "television", "family"],
  ["bedroom", "sleep", "blanket", "pillow"],
  ["garage", "car", "house", "storage_room"],
  ["closet", "clothes", "hiding", "storage_room"],
  ["receiving", "handing_over", "gift", "letter"],
  ["borrowing", "lending", "receiving", "handing_over"],
  ["throwing_away", "tidying", "cleaning", "trash_can"],
  ["rabbit", "child", "family", "grass"],
  ["frog", "rain", "pond", "water"],
  ["turtle", "water", "pond", "shell"],
  ["nurse", "hospital", "injury", "hand"],
  ["grandparent", "family", "ancestor", "past"],
  ["microwave", "kitchen", "cooking", "waiting"],
  ["kettle", "kitchen", "water", "fire"],
  ["laundry_basket", "washing", "clothes", "tidying"],
  ["charging_cable", "charging", "smartphone", "battery_icon"],
  ["shampoo_bottle", "hair", "washing", "toilet"],
  ["bus_stop", "bus", "waiting", "road"],
  ["bakery", "shop", "morning", "buying"],
  ["deer", "forest", "shrine", "grass"],
  ["squirrel", "tree", "park", "concealing"],
  ["returning", "borrowing", "lending", "apologizing"],
  ["mirror_cabinet", "mirror", "makeup", "hair"],
  ["post_office", "letter", "receiving", "waiting"],
  ["playground", "child", "park", "family"],
  ["buying", "shop", "wallet", "choosing"],
  ["paying", "wallet", "money", "shop"],
  ["asking", "voice", "chat", "teacher"],
  ["answering", "voice", "exam", "phone"],
  ["bee", "insect", "flower", "workplace"],
  ["cousin", "family", "childhood_home", "grandparent"],
  ["coach", "teacher", "mentor", "boss"],
];

const conflictCandidatePairs = new Set([
  pairKey("water", "sea"),
  pairKey("water", "river"),
  pairKey("house", "childhood_home"),
  pairKey("school", "exam"),
  pairKey("falling", "flying"),
  pairKey("cat", "dog"),
]);

const staleCandidatePairs = new Set<string>();

function pairKey(a: string, b: string): string {
  return [a, b].sort().join("__");
}

function motifsById(): Map<string, MotifDefinition> {
  return new Map(motifRegistry.motifs.map((motif) => [motif.id, motif]));
}

function sameGroup(sourceId: string, targetId: string, groups: string[][]): boolean {
  return groups.some((group) => group.includes(sourceId) && group.includes(targetId));
}

function detectRelationType(source: MotifDefinition, targetId: string): RelationReviewRecord["relationType"] {
  return source.conflicts?.some((relation) => relation.motifId === targetId) ? "conflict" : "neighbor";
}

export function classifyRelationCluster(sourceId: string, targetId: string): RelationPriorityCluster {
  const ids = new Set([sourceId, targetId]);

  if ([...ids].some((id) => ["water", "sea", "rain", "river", "snow", "thunder", "wind", "fish", "whale", "frog", "turtle", "kettle", "cloud", "rainbow", "lake", "pond", "fog", "wave", "ice", "swimming", "soap", "towel", "washing", "shampoo_bottle", "shell", "dew", "raindrop", "waterweed", "driftwood", "earthquake", "tsunami", "storm", "flood"].includes(id))) {
    return "water-weather";
  }

  if ([...ids].some((id) => ["house", "childhood_home", "hotel", "key", "toilet", "mirror", "shrine", "shop", "library", "park", "door", "restaurant", "cafe", "convenience_store", "cinema", "window", "cave", "island", "living_room", "bedroom", "garage", "closet", "bakery", "post_office", "playground", "mirror_cabinet", "rooftop", "hot_spring", "kitchen", "garden", "hallway", "balcony", "entrance", "doormat", "storage_room", "power_outage", "moving_house", "prison"].includes(id))) {
    return "home-place";
  }

  if ([...ids].some((id) => ["station", "train", "bus", "bus_stop", "car", "airport", "airplane", "travel", "road", "bridge", "stairs", "elevator", "ship", "parking_lot", "map", "ticket", "crossroad", "maze", "bicycle", "climbing", "ladder", "compass", "suitcase", "footprint", "backpack", "dead_end", "traffic_light", "crosswalk", "detour", "turn_back", "sidewalk", "escalator", "platform_edge", "lost_ticket", "pedestrian_bridge", "ticket_gate", "platform_sign", "ticket_machine", "departure_board", "platform_clock", "station_map", "route_sign"].includes(id))) {
    return "movement";
  }

  if ([...ids].some((id) => ["smartphone", "notification", "sns", "email", "phone", "letter", "password", "chat", "charging", "news", "earphone", "television", "radio", "mobile_app", "video", "music", "comment", "streaming"].includes(id))) {
    return "communication";
  }

  if ([...ids].some((id) => ["friend", "family", "stranger", "crowd", "ex_partner", "crush", "breakup", "ring", "boss", "workplace", "child", "teacher", "neighbor", "coworker", "classmate", "nurse", "grandparent", "cousin", "coach", "partner", "rival", "senior", "junior", "relative", "roommate", "customer", "guide", "ancestor", "mentor", "teammate", "bully", "client", "old_friend", "childhood_friend", "leader", "subordinate", "shop_clerk", "guest", "rescuer", "judge", "witness", "captain", "former_classmate", "former_coworker", "online_friend", "police_officer", "admirer", "driver", "landlord", "mediator", "being_fired", "resignation", "wedding", "argument", "reunion", "promotion", "interview", "confession", "betrayal", "divorce", "angel", "god", "demon"].includes(id))) {
    return "relationship";
  }

  if ([...ids].some((id) => ["naked", "injury", "voiceless", "blood", "hospital", "clothes", "hair", "teeth", "eye", "trembling", "hand", "foot", "voice", "pain", "glasses", "hat", "mask", "makeup", "tears", "face", "ear", "mouth", "breath", "brush", "scarf", "forehead", "back", "scar", "necklace", "shoulder", "sleeve", "ankle", "glove", "comb", "eyelash", "fingernail", "cheek", "eyebrow", "chin", "temple", "jawline", "nape", "eyelid", "collarbone"].includes(id))) {
    return "body-appearance";
  }

  if ([...ids].some((id) => ["crying", "laughing", "apologizing", "being_chased", "fighting", "hiding", "searching", "waiting", "lost", "picking_up", "choosing", "opening", "screaming", "forgetting", "running", "cleaning", "tidying", "losing", "handing_over", "receiving", "borrowing", "lending", "returning", "buying", "paying", "asking", "answering", "throwing_away", "embracing", "being_late", "exam", "sleep", "breaking", "making_mistake", "refusing", "lining_up", "tripping", "inviting", "concealing", "cooking", "festival", "writing", "dancing", "packing", "folding", "carrying", "singing", "reading", "tying", "wiping", "wrapping", "unpacking", "carving", "footsteps", "hesitating", "backing_away", "flinching", "tiptoeing", "holding_back", "double_checking", "being_trapped", "paralysis", "transformation", "pregnancy", "graduation", "ghost", "presentation", "apology", "giving_birth"].includes(id))) {
    return "emotion-action";
  }

  if ([...ids].some((id) => ["sky", "moon", "sun", "stars", "bird", "flying", "forest", "mountain", "volcano", "flower", "tree", "insect", "horse", "sand", "desert", "stone", "dark", "morning", "evening", "shadow", "leaf", "grass", "seed", "feather", "nest", "pebble", "maple_leaf", "pinecone", "acorn", "mushroom", "fern", "twig", "moss", "petal", "dust", "stain", "clover", "dandelion", "sprout", "bark", "vine", "root", "bud", "wildflower", "lichen", "reed", "pine_needle", "berry", "daisy", "willow", "lotus", "butterfly", "dragonfly", "owl", "camellia", "ivy", "firefly", "lily_pad", "sparrow", "dragon", "lion", "spider", "bear", "wolf", "fox", "rabbit", "deer", "squirrel", "bee"].includes(id))) {
    return "nature-sky";
  }

  if ([...ids].some((id) => ["photo", "clock", "wallet", "bag", "umbrella", "shoes", "book", "notebook", "box", "desk", "chair", "calendar", "past", "news", "game", "pen", "dish", "shelf", "gift", "planner", "cup", "candle", "blanket", "envelope", "scissors", "sword", "toy", "pillow", "rope", "painting", "button", "coin", "ribbon", "lantern", "drawer", "thread", "stamp", "clay", "bead", "spoon", "blank_page", "knot", "postcard", "basket", "jar", "bench", "curtain", "chalk", "tray", "needle", "paintbrush", "plate", "lamp", "string", "marble", "bucket", "broom", "bowl", "pencil", "bookmark", "shoelace", "zipper", "apron", "ticket_stub", "paint", "keychain", "pocket", "eraser", "ruler", "paperclip", "coaster", "handkerchief", "bell", "ink", "torn_paper", "answer_sheet", "keyboard", "monitor", "glue", "tape", "label", "folder", "receipt", "magnifying_glass", "clipboard", "stapler", "calendar_page", "rubber_band", "binder", "index_card", "coupon", "pencil_case", "checklist", "progress_bar", "loading_icon", "wristwatch", "rubber_stamp", "notepad", "sticky_note", "paper_cup", "file_tab", "pause_button", "status_light", "screen_corner", "name_tag", "paper_crane", "paper_bag", "coin_purse", "corkboard", "measuring_tape", "ink_pad", "cursor", "battery_icon", "mute_button", "binder_clip", "sketchbook", "stamp_sheet", "hourglass", "paperweight", "search_bar", "signal_bar", "volume_slider", "remote_control", "water_bottle", "toothbrush", "keyhole", "trash_can", "refrigerator", "microwave", "kettle", "laundry_basket", "charging_cable", "shampoo_bottle", "mirror_cabinet", "treasure", "money"].includes(id))) {
    return "object-record";
  }

  if ([...ids].some((id) => ["hospital", "nurse", "injury", "blood", "death", "fire", "accident", "surgery", "funeral", "war"].includes(id))) {
    return "care-risk";
  }

  return "general";
}

export function classifyRelationReviewKind(
  sourceId: string,
  targetId: string,
  relationType: RelationReviewRecord["relationType"],
): RelationReviewKind {
  const key = pairKey(sourceId, targetId);

  if (staleCandidatePairs.has(key)) {
    return "stale-relation";
  }

  if (conflictCandidatePairs.has(key)) {
    return relationType === "conflict" ? "generic-specific" : "should-be-conflict";
  }

  if (sameGroup(sourceId, targetId, genericSpecificGroups)) {
    return "generic-specific";
  }

  if (sameGroup(sourceId, targetId, reciprocalCandidateGroups)) {
    return "should-be-reciprocal";
  }

  if (relationType === "conflict") {
    return "should-be-conflict";
  }

  const source = motifRegistry.motifs.find((motif) => motif.id === sourceId);
  const target = motifRegistry.motifs.find((motif) => motif.id === targetId);

  if (source && target && source.category === target.category) {
    return "intentional-one-way";
  }

  return "context-helper";
}

function buildRationale(kind: RelationReviewKind): string {
  switch (kind) {
    case "generic-specific":
      return "汎用motifと具体motifの優先関係としてレビューします。";
    case "should-be-reciprocal":
      return "近縁motif同士として双方向neighbor化の余地をレビューします。";
    case "should-be-conflict":
      return "併存ではなく抑制関係にすべきかをレビューします。";
    case "intentional-one-way":
      return "意味の流れが片方向で成立するため、片方向維持を基本にします。";
    case "stale-relation":
      return "古い設計の可能性があるため削除候補としてレビューします。";
    case "context-helper":
      return "片方が文脈補助として働くため、片方向維持を基本にします。";
  }
}

export function buildRelationReviewRecords(issues: RegistryIssue[] = validateMotifRegistry()): RelationReviewRecord[] {
  const motifById = motifsById();

  return issues
    .filter((issue) => issue.type === "one-way-relation" && issue.motifId && issue.referenceId)
    .map((issue) => {
      const source = motifById.get(issue.motifId!);
      const target = motifById.get(issue.referenceId!);

      if (!source || !target) {
        return null;
      }

      const relationType = detectRelationType(source, target.id);
      const cluster = classifyRelationCluster(source.id, target.id);
      const reviewKind = classifyRelationReviewKind(source.id, target.id, relationType);
      const priority = priorityClusterIds.has(source.id) || priorityClusterIds.has(target.id) ? "high" : "normal";

      return {
        sourceId: source.id,
        targetId: target.id,
        sourceCategory: source.category,
        targetCategory: target.category,
        issueSeverity: issue.severity,
        relationType,
        cluster,
        reviewKind,
        priority,
        rationale: buildRationale(reviewKind),
      };
    })
    .filter((record): record is RelationReviewRecord => Boolean(record));
}

export function summarizeRelationReview(records: RelationReviewRecord[]): RelationReviewSummary {
  return records.reduce<RelationReviewSummary>(
    (summary, record) => ({
      totalOneWayRelations: summary.totalOneWayRelations + 1,
      oneWayInfoRelations: summary.oneWayInfoRelations + (record.issueSeverity === "info" ? 1 : 0),
      oneWayWarningRelations: summary.oneWayWarningRelations + (record.issueSeverity === "warning-review-ok" ? 1 : 0),
      byKind: {
        ...summary.byKind,
        [record.reviewKind]: summary.byKind[record.reviewKind] + 1,
      },
      byCluster: {
        ...summary.byCluster,
        [record.cluster]: summary.byCluster[record.cluster] + 1,
      },
      highPriorityCount: summary.highPriorityCount + (record.priority === "high" ? 1 : 0),
    }),
    {
      totalOneWayRelations: 0,
      oneWayInfoRelations: 0,
      oneWayWarningRelations: 0,
      byKind: Object.fromEntries(relationReviewKinds.map((kind) => [kind, 0])) as Record<RelationReviewKind, number>,
      byCluster: Object.fromEntries(relationPriorityClusters.map((cluster) => [cluster, 0])) as Record<
        RelationPriorityCluster,
        number
      >,
      highPriorityCount: 0,
    },
  );
}
